spring:
    datasource:
        url: jdbc:h2:file:./api-pokemon 
        username: sa
        password: 123
    h2: 
        console: 
            enabled: true
            path: /h2-console
    jpa: 
        hibernate: 
            ddl-auto: update
        show-sql: true
        properties: 
            hibernate: 
                # format_sql: true
        defer-datasource-initialization: true
# server: 
#     error: 
#         include-stacktrace: never